# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [11]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [17]:
arr=np.zeros((10,10))
print("%d bytes" % (arr.size * arr.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [24]:
arr=np.arange(10)
arr=arr[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [31]:
arr=np.array([1,2,0,0,4,0])
for k,i in enumerate(arr):
    if i>0:
        print(k)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [35]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [37]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.06936264 0.31607527 0.23603526]
  [0.89898688 0.87059834 0.88603597]
  [0.87027432 0.53878979 0.32966971]]

 [[0.86917941 0.7341051  0.44839329]
  [0.93207731 0.72819028 0.7194496 ]
  [0.21081332 0.23406293 0.52052152]]

 [[0.5256742  0.88982743 0.53880856]
  [0.84169782 0.75079009 0.31585423]
  [0.51904947 0.57352407 0.56939729]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
arr=np.random.random((10,10))
print(arr)
print(arr.max())
print(arr.min())

[[0.14054718 0.27526902 0.34525579 0.22104293 0.03425778 0.67544013
  0.57093369 0.45145431 0.98090751 0.84062073]
 [0.15479096 0.49115196 0.62043905 0.11022776 0.03084    0.8209823
  0.61447531 0.56750364 0.9766069  0.39236355]
 [0.85051845 0.24254278 0.01220569 0.02718767 0.96469835 0.22056819
  0.95516425 0.64579488 0.86110881 0.10813672]
 [0.85342217 0.00804109 0.08424859 0.51704497 0.21955421 0.22443787
  0.44368201 0.93504769 0.78146933 0.45742653]
 [0.35341938 0.88237243 0.31466513 0.30146205 0.92524554 0.56759362
  0.41844921 0.81068619 0.92525844 0.41983993]
 [0.8164079  0.06936434 0.43873268 0.17923332 0.37923731 0.1961089
  0.97781727 0.96856945 0.50511061 0.38777646]
 [0.60515718 0.26206851 0.88925637 0.31011343 0.45873967 0.66066076
  0.7439995  0.55045472 0.50264122 0.90202892]
 [0.43499802 0.22623075 0.74164626 0.90974444 0.93442283 0.79256321
  0.70306714 0.61827053 0.84495733 0.18087714]
 [0.28646208 0.01733263 0.30900111 0.25778075 0.47834196 0.8188503
  0.66395242 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [39]:
arr=np.random.random(30)
print(arr)
print(arr.mean())

[0.67363675 0.511499   0.90585825 0.15449078 0.5264197  0.20459322
 0.32871099 0.03061008 0.36183016 0.1542667  0.22236167 0.65768176
 0.4918094  0.57442379 0.01313664 0.18528675 0.33610085 0.00738583
 0.64720478 0.98723203 0.69889994 0.47711732 0.66701747 0.06616326
 0.97869023 0.98564207 0.73378025 0.38389144 0.1329733  0.8318241 ]
0.4643512840687728


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [48]:
arr=np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [70]:
arr=np.zeros((5,5))
arr[1:-1:,1:-1]=1
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [66]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [72]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


In [71]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [87]:
arr=np.eye(5)
for i in range(arr.shape[0]-1):
    arr[i+1][i]=i+1
print(arr)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


In [90]:
arr=np.eye(5)
arr=np.diag(1+np.arange(4), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [88]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [95]:
arr=np.zeros((8,8))
arr[0:8:2, 0:8:2]=1
arr[1:8:2, 1:8:2]=1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [96]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [112]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [110]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [113]:
arr=np.tile([[0,1],[1,0]],[4,4])
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [116]:
arr=np.random.random((5,5))
arr=(arr-np.mean(arr))/np.std(arr)
print(arr)

[[ 0.45398163 -1.19027548 -0.09991353  0.4950243   0.59973435]
 [ 0.28538895 -1.06405072  1.48088253  0.03272965 -1.54682449]
 [ 0.51729763  1.55946036 -0.61522981  0.63812718 -1.54039369]
 [ 1.51633465 -1.26401576  0.57110973  1.29420733  0.03185031]
 [-1.34986657  0.74111215 -0.90560675  0.63021471 -1.27127869]]


In [115]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


In [117]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.36089724 -1.32410629 -0.58291448 -0.46782641  0.33513058]
 [-1.28841294  1.63141826 -0.97878739  0.91081794 -1.2453386 ]
 [ 1.23778736 -1.34975439 -0.10166072  0.40738461 -0.57082853]
 [ 1.15761882  1.12378931  0.24097675 -0.22590878 -0.88578236]
 [ 2.15066696 -0.00547437 -0.73236811 -0.49787887  1.42234888]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [121]:
d=np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
print(d)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [120]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [122]:
arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
print(arr1)
print(arr2)
print(arr1.dot(arr2))

[[0.72271872 0.04519096 0.4934378 ]
 [0.07092434 0.6299237  0.41082914]
 [0.21012014 0.74911922 0.93594106]
 [0.57078785 0.9217346  0.7526314 ]
 [0.24419081 0.97482802 0.02548373]]
[[0.04684397 0.83659704]
 [0.59784175 0.81271248]
 [0.87353523 0.46481071]]
[[0.49190736 0.87070677]
 [0.7387908  0.76223973]
 [1.2752751  1.21963986]
 [1.23523944 1.57645577]
 [0.61649269 1.00838931]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [131]:
arr=np.random.random(5)*(10)
print(arr)
for k,i in enumerate(arr):
    if i>=3 and i<=8:
        arr[k]=arr[k]*(-1)
print(arr)

[9.74659917 9.0429452  6.03245693 3.01678928 4.37771838]
[ 9.74659917  9.0429452  -6.03245693 -3.01678928 -4.37771838]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [132]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [133]:
answer(26)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [134]:
answer(27)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


In [136]:
Z=np.arange(4)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>

SyntaxError: invalid syntax (1513249350.py, line 7)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [137]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\riyaa\AppData\Local\Temp\ipykernel_5180\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\riyaa\AppData\Local\Temp\ipykernel_5180\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\riyaa\AppData\Local\Temp\ipykernel_5180\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

In [138]:
answer(28)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [140]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


In [3]:
arr=np.random.uniform(-10,10,10)
print(arr)
arr=np.copysign(np.ceil(np.abs(arr)),arr)
print(arr)

[ 1.45407795  9.80606106  5.24451708 -4.54449616 -5.41482404  1.31181981
  9.43846871  0.02023157  9.42493271  0.32754997]
[ 2. 10.  6. -5. -6.  2. 10.  1. 10.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [24]:
arr1=np.arange(6)
arr2=np.arange(start=2,stop=8,step=1)
print(np.intersect1d(arr1,arr2))

[2 3 4 5]


In [22]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [25]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [26]:
defaults=np.seterr(all="ignore")
arr = np.ones(1)/0

_=np.seterr(**defaults)

with np.errstate(all="ignore"):
    np.arange(3)/0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [27]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\riyaa\AppData\Local\Temp\ipykernel_7640\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


In [28]:
answer(32)

np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [29]:
answer(33)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


In [32]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)
print(yesterday,today,tomorrow)

2024-12-18 2024-12-19 2024-12-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [3]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


In [5]:
arr=np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [6]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [12]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=a)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)

[-3. -3. -3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [3]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


In [4]:
arr=np.random.uniform(0,10,10)
print(arr-arr%1)
print(arr//1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[6. 4. 5. 4. 3. 4. 4. 6. 4. 6.]
[6. 4. 5. 4. 3. 4. 4. 6. 4. 6.]
[6. 4. 5. 4. 3. 4. 4. 6. 4. 6.]
[6 4 5 4 3 4 4 6 4 6]
[6. 4. 5. 4. 3. 4. 4. 6. 4. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [7]:
arr=np.arange(5)
arr=arr+np.zeros((5,5))
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [8]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


In [11]:
def generate():
    for i in range(10):
        yield i
arr=np.fromiter(generate(),dtype=float, count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [13]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


In [16]:
arr=np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [20]:
arr=np.random.random(10)
arr.sort()
print(arr)

[0.11435258 0.23640864 0.3045432  0.40862602 0.41638426 0.44836931
 0.68273031 0.71011064 0.84715292 0.90817091]


In [18]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [22]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


In [23]:
arr=np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [28]:
arr1=np.arange(10)
arr2=np.arange(15)
print(np.array_equal(arr1,arr2))

False


In [27]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [29]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


In [30]:
arr=np.zeros(10)
arr.flags.writeable = False
arr[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [32]:
arr=np.random.random((10,2))
x,y=arr[:,0], arr[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.84499112 0.85066753 0.6364644  1.05944645 1.11521099 1.07540205
 0.92433508 0.75453492 0.84083534 0.94914212]
[0.92699428 0.93648835 0.34694717 1.05340797 0.56827676 0.48917141
 0.11072008 0.54412643 0.83257752 1.29287848]


In [31]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
arr=np.random.random(10)
print(arr)
arr[arr.argmax()]=0
print(arr)

[0.25849209 0.76320633 0.37770662 0.68745085 0.64913575 0.96746364
 0.91531367 0.64816002 0.56016589 0.74702255]
[0.25849209 0.76320633 0.37770662 0.68745085 0.64913575 0.
 0.91531367 0.64816002 0.56016589 0.74702255]


In [35]:
answer(45)

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [37]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


In [38]:
arr=np.zeros((5,5), [('x',float),('y', float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [42]:
x=np.random.random(5)
y=np.random.random(5)
c=np.zeros(5)
c=1.0/np.subtract.outer(x,y)
print(x)
print(y)
print(c)

[0.77620116 0.92917608 0.77136925 0.20625151 0.42948401]
[0.08518198 0.8513609  0.72018588 0.30558523 0.2220785 ]
[[  1.44713783 -13.30499442  17.85227162   2.12487495   1.80465459]
 [  1.18484239  12.85096325   4.78491325   1.60361557   1.41423196]
 [  1.45732811 -12.5013034   19.53759698   2.14691781   1.82052949]
 [  8.25971612  -1.55012469  -1.94577375 -10.06707511 -63.18321581]
 [  2.90442662  -2.37035973  -3.43995039   8.07110435   4.82147263]]


In [40]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [43]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆)

In [46]:
np.set_printoptions(threshold=float("inf"))
arr=np.random.random((10,10))
print(arr)

[[0.45171205 0.79064237 0.99846225 0.23613915 0.56816072 0.39229194
  0.04588927 0.38492156 0.08617003 0.23910817]
 [0.84873786 0.82672786 0.68833448 0.20178244 0.01483738 0.52357336
  0.32809386 0.04581458 0.22686239 0.86226939]
 [0.24655171 0.51466545 0.07558705 0.43956742 0.3043403  0.69136932
  0.64318759 0.05220804 0.48851562 0.7458908 ]
 [0.04396915 0.16887019 0.58032759 0.51993077 0.33209021 0.99812391
  0.09837545 0.50345826 0.62960204 0.90336339]
 [0.72206551 0.38456647 0.88497505 0.22970037 0.33499739 0.46196882
  0.35520117 0.1337183  0.99868414 0.35448567]
 [0.19854208 0.85966524 0.20646736 0.19177159 0.43895885 0.82445967
  0.95061022 0.85643768 0.73694224 0.46388375]
 [0.05415646 0.97667257 0.47531449 0.64523766 0.77997856 0.36428991
  0.06790888 0.57324743 0.81865699 0.53425238]
 [0.40603749 0.53096482 0.35056633 0.28528908 0.54558794 0.04893005
  0.76507032 0.55371969 0.32576945 0.09906197]
 [0.69066921 0.11050562 0.20336606 0.83100106 0.97616166 0.74215967
  0.58744506

In [45]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [47]:
answer(50)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [55]:
arr=np.zeros(10, [('position',[('x',float),('y',float)]),('color',[('r',float),('g',float),('b',float)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [49]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [61]:
arr=np.random.random((100,2))
x=arr[:,0].reshape(1,100)
y=arr[:,1].reshape(1,100)
arr2=np.sqrt((x-x.T)**2+(y-y.T)**2)
print(arr2)

[[0.         0.2012624  0.90733615 0.71058661 0.73535918 0.72337852
  0.19078513 0.19862687 0.88048641 0.73802407 0.47647723 0.44225783
  0.81457371 0.86280962 0.66470269 0.45600407 0.32739979 0.25239277
  0.50586412 0.90434397 0.17612913 0.36260337 0.55894386 0.519007
  0.36003881 0.83207321 0.59561301 0.18050556 0.75953857 0.49410475
  0.69109571 0.68726028 0.55885138 0.675499   0.70205165 0.6087573
  0.3543347  0.13966193 0.72728566 0.41627939 0.72353534 0.78350444
  0.92218411 0.30198861 0.75233841 1.01475437 0.67137527 0.67181883
  0.79562858 0.86011666 0.93856904 0.49828126 0.74427057 0.40171011
  0.32920297 0.61378869 0.86282533 0.953127   0.23771159 0.8647558
  0.67173729 0.14263952 0.92526181 0.56415323 0.19913131 0.53105577
  0.8864142  0.66499577 0.86185804 0.52703365 0.56363006 0.14629785
  0.90392511 0.20051928 0.68597229 0.70014805 0.78817163 0.54425045
  0.61775122 0.48352625 0.10631147 0.71095924 0.27209835 0.93147777
  0.4212843  0.57404427 0.97114719 0.91262907 0.3475

In [57]:
answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [65]:
arr=np.random.random((10,10)).astype(np.float32)
print(arr)
print(arr.astype(np.int32))

[[0.1950612  0.15539007 0.94674546 0.43643558 0.03664499 0.72296923
  0.9753473  0.19688678 0.7157898  0.00118589]
 [0.22596937 0.63832164 0.03283332 0.57811767 0.01521389 0.80709004
  0.766971   0.6530469  0.53654486 0.07301008]
 [0.9801039  0.19451064 0.7993302  0.4690622  0.97076434 0.63870084
  0.6930002  0.03430749 0.7306453  0.72873676]
 [0.05587023 0.5080846  0.55845445 0.82253516 0.7870052  0.79990834
  0.34820038 0.95021266 0.06971969 0.84671694]
 [0.43380415 0.45401353 0.24723779 0.04689299 0.00516266 0.47154927
  0.81270033 0.38234165 0.22907759 0.6616743 ]
 [0.8818105  0.67584336 0.17991969 0.36709037 0.99506354 0.7026363
  0.07403968 0.45047092 0.06196657 0.5034707 ]
 [0.6652324  0.16494933 0.06856582 0.46186805 0.44380167 0.18331113
  0.2175193  0.47463498 0.46008265 0.90078366]
 [0.76078933 0.8962618  0.47590324 0.60162336 0.51770616 0.9157164
  0.17192957 0.35306498 0.30810028 0.15062341]
 [0.0591062  0.7852363  0.6427345  0.8081179  0.28453156 0.4435344
  0.9800133  0.

In [64]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


In [69]:
from io import StringIO
s=StringIO('''1,2,3,4,5,6, , ,7,8, ,9,10,11''')
arr=np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(arr)

[ 1  2  3  4  5  6 -1 -1  7  8 -1  9 10 11]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [71]:
answer(55)

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [72]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [73]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [75]:
answer(58)

# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

In [76]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [77]:
answer(60)

# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


#### 61. Find the nearest value from a given value in an array (★★☆)

In [78]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [79]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


#### 63. Create an array class that has a name attribute (★★☆)

In [80]:
answer(63)

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [81]:
answer(64)

# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [82]:
answer(65)

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [83]:
answer(66)

# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [84]:
answer(67)

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [85]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [86]:
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [87]:
answer(70)

# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [88]:
answer(71)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★)

In [89]:
answer(72)

# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [90]:
answer(73)

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [91]:
answer(74)

# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [92]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [93]:
answer(76)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [94]:
answer(77)

# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [95]:
answer(78)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [96]:
answer(79)

# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [97]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [98]:
answer(81)

# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


#### 82. Compute a matrix rank (★★★)

In [99]:
answer(82)

# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)


#### 83. How to find the most frequent value in an array?

In [100]:
answer(83)

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [101]:
answer(84)

# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [102]:
answer(85)

# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [103]:
answer(86)

# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [104]:
answer(87)

# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

# Author: Jeff Luo (@Jeff1999)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [105]:
answer(88)

# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


#### 89. How to get the n largest values of an array (★★★)

In [106]:
answer(89)

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [107]:
answer(90)

# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


#### 91. How to create a record array from a regular array? (★★★)

In [108]:
answer(91)

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [109]:
answer(92)

# Author: Ryan G.

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [110]:
answer(93)

# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [111]:
answer(94)

# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [112]:
answer(95)

# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [113]:
answer(96)

# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [114]:
answer(97)

# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [115]:
answer(98)

# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [116]:
answer(99)

# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [117]:
answer(100)

# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)
